version: 2
updates:
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "weekly"
  versioning-strategy: auto
  labels:
  - "npm"
  - "dependencies"
  commit-message:
    prefix: "chore"
    include: "scope"
  groups:
    dependencies:
      patterns:
      - "*"
  ignore:
  - dependency-name: "typescript"
    versions: ["5.x"]
  open-pull-requests-limit: 10
  reviewers:
  - "felipebarcelospro"
  security-updates-only: true
