name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
- title: '💥 Breaking Changes'
  labels:
  - 'breaking'
- title: '🚀 Features'
  labels:
  - 'feature'
  - 'enhancement'
- title: '🐛 Bug Fixes'
  labels:
  - 'fix'
  - 'bug'
- title: '🧰 Maintenance'
  labels:
  - 'chore'
  - 'maintenance'
- title: '📚 Documentation'
  labels:
  - 'docs'
- title: '⬆️ Dependencies'
  labels:
  - 'dependencies'
- title: '🔒 Security'
  labels:
  - 'security'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions

version-resolver:
  major:
    labels:
    - 'major'
    - 'breaking'
  minor:
    labels:
    - 'minor'
    - 'feature'
  patch:
    labels:
    - 'patch'
    - 'fix'
    - 'bugfix'
    - 'bug'
    - 'maintenance'
  default: patch

template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/felipebarcelospro/drift/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

  ## 👨‍💻 Contributors

  $CONTRIBUTORS

exclude-labels:
- 'skip-changelog'

autolabeler:
- label: 'bug'
  branch:
  - '/fix\/.+/'
  title:
  - '/fix/i'
- label: 'enhancement'
  branch:
  - '/feature\/.+/'
  title:
  - '/feat/i'
- label: 'documentation'
  branch:
  - '/docs\/.+/'
  title:
  - '/docs/i'
- label: 'maintenance'
  branch:
  - '/chore\/.+/'
  title:
  - '/chore/i'
- label: 'dependencies'
  branch:
  - '/deps\/.+/'
  title:
  - '/deps/i'
