name: Publish Package

on:
  push:
    tags:
      - 'v*'

jobs:  
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org/'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build packages
        run: npm run build
      
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
      - name: Publish to NPM
        run: npm run publish-packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          VERSION: ${{ steps.get_version.outputs.VERSION }}
      
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v2
      
      - name: Publish to Deno
        run: deno publish
        env:
          DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}
      
      - name: Publish to JSR
        run: npx jsr publish
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: packages/*/dist/**
          generate_release_notes: true
          body_path: .github/RELEASE_NOTES.md