name: Publish Package

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit

      - name: Run tests
        run: npm run test
      
      - name: Build packages
        run: |
          cd packages/core
          npm run build
      
      - name: Cache artifacts
        uses: actions/cache@v3
        with:
          path: |
            packages/core/dist
            packages/core/deno
            node_modules
          key: build-${{ github.sha }}

  publish-npm:
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'
      
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            packages/core/dist
            node_modules
          key: build-${{ github.sha }}
      
      

  create-release:
    needs: [publish-npm]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            packages/core/dist
            packages/core/deno
          key: build-${{ github.sha }}
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            packages/core/dist/**
            packages/core/deno/**
          generate_release_notes: true
          body_path: .github/RELEASE_NOTES.md