name: Publish Package

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit
      
      - name: Build packages
        run: |
          cd packages/core
          npm run build
      
      - name: Cache artifacts
        uses: actions/cache@v3
        with:
          path: |
            packages/core/dist
            packages/core/deno
            node_modules
          key: build-${{ github.sha }}

  publish-npm:
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'
      
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            packages/core/dist
            node_modules
          key: build-${{ github.sha }}
      
      - name: Update version
        run: cd packages/core && npm version ${{ needs.setup.outputs.version }} --no-git-tag-version
      
      - name: Publish to NPM
        run: cd packages/core && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-deno:
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v2
      
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: packages/core/deno
          key: build-${{ github.sha }}
      
      - name: Update version
        run: |
          cd packages/core
          jq '.version = "${{ needs.setup.outputs.version }}"' deno.json > temp.json && mv temp.json deno.json
      
      - name: Publish to Deno
        run: cd packages/core && deno publish
        env:
          DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}

  create-release:
    needs: [publish-npm, publish-deno]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            packages/core/dist
            packages/core/deno
          key: build-${{ github.sha }}
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            packages/core/dist/**
            packages/core/deno/**
          generate_release_notes: true
          body_path: .github/RELEASE_NOTES.md