name: Sync Roadmap

on:
  push:
    branches:
      - main

jobs:
  setup-and-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install @octokit/rest@19.0.13 @actions/core

      - name: Create or Get Project
        id: get-project
        run: |
          node .github/scripts/create-project.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync Roadmap
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECT_ID: ${{ steps.get-project.outputs.project_id }}
        run: |
          node .github/scripts/sync-roadmap.js

  check:
    needs: setup-and-sync
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Check if all jobs succeeded
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}