name: Update Changelog

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Generate Changelog
        run: npx auto-changelog --commit-limit false --starting-version 0.1.0
        
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update CHANGELOG.md [skip ci]"
          file_pattern: CHANGELOG.md