name: Welcome First Time Contributors

on:
  pull_request_target:
    types: [opened]
  issues:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            👋 Thanks for opening your first issue in Drift KV! We'll review it soon.
            
            Meanwhile, please make sure you've read our [contributing guidelines](CONTRIBUTING.md).
          pr-message: |
            🎉 Thanks for opening your first pull request in Drift KV!
            
            We'll review your contribution soon. Please make sure all checks are passing.
